const ERROR_MESSAGES = {
    EMAIL_PASSWORD_REQUIRED: 'Email and password are required',
    INVALID_CREDENTIALS: 'Invalid email or password',
    FAILED_TO_REGISTER: 'Failed to register user',
    FAILED_TO_LOGIN: 'Failed to login',
    TOKEN_REQUIRED: 'Authentication token is required',
    INVALID_TOKEN: 'Invalid token',
    INVALID_SESSION: 'Invalid or expired session',
    FAILED_TO_LOGOUT: 'Failed to logout',
    TEXT_TARGETLANG_REQUIRED: 'Text and target language are required. Please try again.',
    FAILED_TO_TRANSLATE: 'Failed to translate the text. Please ensure the text is translatable and try again.',
    IMAGE_DATA_REQUIRED: 'Image data is required. Please try again.',
    FAILED_TO_RECOGNIZE_TEXT: 'Failed to recognize text from image. Please ensure the image contains readable text and try again.',
    AUDIO_FILE_REQUIRED: 'Audio file is required',
    INVALID_AUDIO_FORMAT: 'Uploaded file is not a valid audio format',
    INVALID_FILE_PATH: 'Uploaded file path is invalid or does not exist',
    FAILED_TO_TRANSCRIBE: 'Failed to transcribe speech',
    TEXT_LANGUAGE_REQUIRED: 'Text and language are required',
    FAILED_TO_GENERATE_SPEECH: 'Failed to generate speech',
    FAILED_TO_RECOGNIZE_ASL: 'Failed to recognize ASL gesture. Note: Vision models may struggle with spatial reasoning required for accurate ASL interpretation.',
    FILE_URI_REQUIRED: 'File URI is required',
    UNSUPPORTED_FILE_TYPE: 'Unsupported file type. Only .pdf, .docx, or .txt are supported.',
    FAILED_TO_EXTRACT_TEXT: 'Failed to extract text from file',
    TEXT_REQUIRED: 'Text is required',
    FAILED_TO_GENERATE_DOC: 'Failed to generate document',
    FAILED_TO_SAVE_TEXT_TRANSLATION: 'Failed to save text translation',
    FAILED_TO_FETCH_TEXT_TRANSLATIONS: 'Failed to fetch text translations',
    FAILED_TO_SAVE_VOICE_TRANSLATION: 'Failed to save voice translation',
    FAILED_TO_FETCH_VOICE_TRANSLATIONS: 'Failed to fetch voice translations',
    FAILED_TO_DELETE_TRANSLATION: 'Failed to delete translation',
    FAILED_TO_CLEAR_TRANSLATIONS: 'Failed to clear translations',
    FAILED_TO_FETCH_STATISTICS: 'Failed to fetch language statistics',
    FAILED_TO_FETCH_AUDIT_LOGS: 'Failed to fetch audit logs',
    QUERY_PARAM_REQUIRED: 'Query parameter is required',
    FAILED_TO_SEARCH_LANGUAGES: 'Failed to search languages',
    LOGIN_REQUIRED: 'Login required to translate files.',
  };
  
  module.exports = { ERROR_MESSAGES };